In [1]:
import numpy as np
import pandas as pd

In [2]:
pd.__version__

'3.0.6'

In [ ]:
!wget https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv

In [5]:
df = pd.read_csv("https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv")

In [6]:
df.describe().round(2)

,model_year,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
count,10000.00,10000.00,10000.00,10000.00,9123.00,10000.00,9736.00,10000.00
mean,1999.55,3.50,2268.81,6.04,254.45,4286.75,18.89,30.00
std,14.21,0.95,183.45,0.54,22.84,266.21,1.28,2.93
min,1975.00,2.00,1590.00,4.00,171.00,3320.00,14.00,19.80
25%,1987.00,3.00,2150.00,6.00,239.00,4110.00,18.00,28.00
50%,2000.00,4.00,2270.00,6.00,254.00,4280.00,18.90,30.00
75%,2012.00,4.00,2390.00,6.00,270.00,4470.00,19.70,31.90
max,2024.00,5.00,3110.00,8.00,334.00,5460.00,23.80,41.20

In [8]:
len(df)                # number of rows
             # non-null count per column

10000

In [9]:
df.columns

Index(['model_year', 'origin', 'fuel_type', 'drivetrain', 'num_doors',
       'engine_displacement', 'num_cylinders', 'horsepower', 'vehicle_weight',
       'acceleration', 'fuel_efficiency_mpg'],
      dtype='str')

In [10]:
df['fuel_type'].unique()

<StringArray>
['Gasoline', 'Diesel', 'Hybrid']
Length: 3, dtype: str

In [12]:
df.isnull().sum()  # Missing values

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [42]:
df.columns[df.isnull().any()]   # Columns with missing values

Index(['horsepower', 'acceleration'], dtype='str')

In [15]:
# Maximum Fuel efficiency
df.loc[df['fuel_efficiency_mpg'].idxmax()]

model_year                          2022
origin                              Asia
fuel_type                         Diesel
drivetrain             Front-wheel drive
num_doors                              4
engine_displacement                 1990
num_cylinders                          6
horsepower                         225.0
vehicle_weight                      3870
acceleration                        17.2
fuel_efficiency_mpg                 41.2
Name: 6354, dtype: object

In [17]:
original_median = df['horsepower'].median()
print(original_median)

254.0

In [20]:
mode_value = df['horsepower'].mode()[0] 
print(mode_value)

252.0

In [21]:
df['horsepower_filled'] = df['horsepower'].fillna(mode_value) 
new_median = df['horsepower_filled'].median() 
print(new_median)

252.0

In [23]:
print(f"Original: {original_median}, After filling: {new_median}")

if new_median > original_median:
    print("Yes, it increased")
elif new_median < original_median:
    print("Yes, it decreased")
else:
    print("No")

Original: 254.0, After filling: 252.0
Yes, it decreased

In [27]:
df_asia = df[df['origin'] == 'Asia'] # Select all cars from Asia
df_asia

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg,horsepower_filled
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5,267.0
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8,250.0
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9,251.0
10,1978,Asia,Gasoline,All-wheel drive,3,2410,6,NaN,4420,19.5,26.8,252.0
15,2007,Asia,Diesel,Front-wheel drive,4,2170,5,226.0,3950,18.0,35.4,226.0
...,...,...,...,...,...,...,...,...,...,...,...,...
9984,2011,Asia,Gasoline,Front-wheel drive,3,2410,6,256.0,4610,20.2,32.4,256.0
9987,2004,Asia,Diesel,All-wheel drive,3,2180,6,266.0,4530,18.6,29.0,266.0
9990,1975,Asia,Diesel,Front-wheel drive,4,1940,6,236.0,3630,19.7,32.4,236.0
9994,1993,Asia,Gasoline,Rear-wheel drive,2,2360,6,257.0,4610,22.2,30.1,257.0
9996,1993,Asia,Gasoline,All-wheel drive,2,2300,6,244.0,4370,19.0,30.0,244.0

In [28]:
df_asia = df_asia[['vehicle_weight', 'model_year']]  # Only vehicle weight & model_year columns
df_asia

      vehicle_weight  model_year
2               4240        1996
6               4310        1992
8               4230        1997
10              4420        1978
15              3950        2007
...              ...         ...
9984            4610        2011
9987            4530        2004
9990            3630        1975
9994            4610        1993
9996            4370        1993

[2994 rows x 2 columns]

In [30]:
df_asia = df_asia.head(7) # First Seven values
df_asia

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [31]:
X = df_asia.values # NumPy array (X)
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [33]:
XTX = X.T.dot(X) #XTX = Xᵀ · X
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [35]:
XTX_inv = np.linalg.inv(XTX) # Inverse of the matrix
XTX_inv

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [37]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200]) # y array
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [38]:
w = XTX_inv.dot(X.T).dot(y) # Compute w = (XᵀX)⁻¹ · Xᵀ · y

In [41]:
float(w.sum())

0.36919696904925203